services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BeardCoder\MensCircle\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Controllers must be public
  BeardCoder\MensCircle\Controller\EventController:
    public: true
    tags: ['extbase.controller']

  BeardCoder\MensCircle\Controller\NewsletterController:
    public: true
    tags: ['extbase.controller']

  BeardCoder\MensCircle\Controller\TestimonialController:
    public: true
    tags: ['extbase.controller']

  # Event Listeners via PHP attributes - no manual tag needed
  # but kept here for clarity
  BeardCoder\MensCircle\EventListener\RegistrationCreatedListener:
    tags:
      - name: event.listener
        identifier: 'mens-circle/registration-created'

  BeardCoder\MensCircle\EventListener\NewsletterSubscribedListener:
    tags:
      - name: event.listener
        identifier: 'mens-circle/newsletter-subscribed'

  # Repositories must be public for Extbase
  BeardCoder\MensCircle\Domain\Repository\EventRepository:
    public: true

  BeardCoder\MensCircle\Domain\Repository\RegistrationRepository:
    public: true

  BeardCoder\MensCircle\Domain\Repository\NewsletterSubscriptionRepository:
    public: true

  BeardCoder\MensCircle\Domain\Repository\TestimonialRepository:
    public: true

  # Dashboard Widgets
  dashboard.widget.menscircle.newsletterSubscriberCount:
    class: 'BeardCoder\MensCircle\Widgets\NewsletterSubscriberCountWidget'
    tags:
      - name: dashboard.widget
        identifier: 'menscircle-newsletter-subscriber-count'
        groupNames: 'menscircle'
        title: 'LLL:EXT:mens_circle/Resources/Private/Language/locallang.xlf:widget.newsletterSubscriberCount.title'
        description: 'LLL:EXT:mens_circle/Resources/Private/Language/locallang.xlf:widget.newsletterSubscriberCount.description'
        iconIdentifier: 'content-form'
        height: 'small'
        width: 'small'

  dashboard.widget.menscircle.latestNewsletterSubscriber:
    class: 'BeardCoder\MensCircle\Widgets\LatestNewsletterSubscriberWidget'
    tags:
      - name: dashboard.widget
        identifier: 'menscircle-latest-newsletter-subscriber'
        groupNames: 'menscircle'
        title: 'LLL:EXT:mens_circle/Resources/Private/Language/locallang.xlf:widget.latestNewsletterSubscriber.title'
        description: 'LLL:EXT:mens_circle/Resources/Private/Language/locallang.xlf:widget.latestNewsletterSubscriber.description'
        iconIdentifier: 'content-form'
        height: 'medium'
        width: 'small'

  dashboard.widgetGroup.menscircle:
    class: 'stdClass'
    synthetic: true
    tags:
      - name: dashboard.widgetGroup
        identifier: 'menscircle'
        title: 'LLL:EXT:mens_circle/Resources/Private/Language/locallang.xlf:widget.group.menscircle'

