services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MarkusSommer\MensCircle\:
    resource: '../Classes/*'

  MarkusSommer\MensCircle\Controller\:
    resource: '../Classes/Controller/*'
    public: true
