# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.5.0"

[source]
workspace = "."
paths = ["app/", "database/factories/", "database/seeders/", "tests/"]
includes = ["vendor"]
excludes = []

[formatter]
preset = "default"
print-width = 140

[linter]
integrations = ["laravel", "pest"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }
no-literal-password = { enabled = false }
too-many-methods = { threshold = 25 }
too-many-enum-cases = { enabled = false }
cyclomatic-complexity = { threshold = 200 }
kan-defect = { enabled = false }
excessive-parameter-list = { threshold = 12 }

[analyzer]
plugins = []
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = false
memoize-properties = true
allow-possibly-undefined-array-keys = false
check-throws = true
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true

