categories:
  mensCircle:
    label: 'Männerkreis'

settings:
  mensCircle.siteName:
    label: 'Seitenname'
    category: mensCircle
    type: string
    default: 'Männerkreis Niederbayern/ Straubing'
  mensCircle.contactEmail:
    label: 'Kontakt E-Mail'
    category: mensCircle
    type: string
    default: 'hallo@example.com'
  mensCircle.baseUrl:
    label: 'Basis-URL für Links in E-Mails'
    category: mensCircle
    type: string
    default: ''
  mensCircle.theme:
    label: 'Theme'
    category: mensCircle
    type: string
    default: 'earth'
    enum:
      earth: 'Earth'
      sand: 'Sand'
      forest: 'Forest'
  mensCircle.storagePid:
    label: 'Storage PID'
    category: mensCircle
    type: int
    default: 1
  mensCircle.newsletterPid:
    label: 'Newsletter PID'
    category: mensCircle
    type: int
    default: 1
  mensCircle.whatsappCommunityLink:
    label: 'WhatsApp Community Link'
    category: mensCircle
    type: string
    default: ''
  mensCircle.smsEnabled:
    label: 'SMS Benachrichtigungen aktiv'
    category: mensCircle
    type: bool
    default: false
  mensCircle.smsSender:
    label: 'SMS Absender'
    category: mensCircle
    type: string
    default: 'MensCircle'
